[workspace]
members = [
    "crates/oil_lex",
    "crates/oil_ast",
    "crates/oil_common",
    "crates/oil_parse",
    "crates/oil",
    "crates/oil_ir",
    "crates/oil_gen",
    "crates/oil_compile",
    "crates/oil_pm",
    "crates/oil_typeck", "crates/oil_cfa",
]
resolver = "3"
